# description:  Will add FSLogix SW to a running VM (via custom script extension)
# dependson: there must be an existing host pool with running vms
# owner: bfrank
#########################

name: 'AVD PoC FSLogix session hosts setup with classic DC pipeline'

parameters:
  - name: groupSelection
    displayName: Deployment environment variable file to use
    type: string
    default: ..\bfrankvs.pipeline.variables.yml
    values:
    - ..\bfrankcsp.pipeline.variables.yml
    - ..\bfrankvs.pipeline.variables.yml
#The Azure file share to connect to 
  - name: VMNames
    type: object
    default: [vm1, vm2]
  - name: ResourceGroupVMs
    default: rg-avdPoC-HP1

variables:
 - template: ${{ parameters.groupSelection }} #based on user input (see parameter above) we select the ...variables.yml file which defines the target environment 
  
trigger: none

stages:
  - stage: Publish
    displayName: Publish
    jobs:
      - job: PublishJob
        displayName: Copy and publish artefacts
        steps:
          - task: CopyFiles@2
            displayName: Copy ARM templates
            inputs:
              sourceFolder: pipelines/fslogix
              contents: |
                **/pipelines/fslogix/setupartefacts/**
                **/fslogix/setupartefacts/**
                **/setupartefacts/**
                **\pipelines\fslogix\setupartefacts\**
                **\fslogix\setupartefacts\**
                **\setupartefacts\**
                *.json
              targetFolder: $(Build.ArtifactStagingDirectory)/${{ variables.artifactDropName }}
          - task: PublishPipelineArtifact@1
            displayName: Publish artefacts
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)/${{ variables.artifactDropName }}"
              artifact: ${{ variables.artifactDropName }}


  - stage: DeployARM
    displayName: ARM Deployments
    jobs:
      - job:
        displayName: Deploy Azure premium fileshare for FSLogix profiles
      - deployment: Deploy
        environment: $(azureResourceManagerConnection)
        pool:
          vmImage: windows-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureResourceGroupDeployment@2
                  displayName: Deploy storage account for FSLOGIX setup artefacts (PowerShell scripts) via ARM template
                  inputs:
                    azureSubscription: $(azureResourceManagerConnection)
                    action: "Create Or Update Resource Group"
                    resourceGroupName: $(rgForSharedResources)
                    location: $(location)
                    templateLocation: "Linked artifact"
                    csmFile: $(Pipeline.Workspace)/${{ variables.artifactDropName }}/artefactsstorageaccount.json
                    overrideParameters: '-saPrefix "$(saPrefix)"'
                    deploymentOutputs: "armOutputs"
              
                - task: PowerShell@2
                  displayName: Prepare pipeline variables - SAS token to storage account
                  inputs:
                    targetType: "inline"
                    script: |
                      # Write your PowerShell commands here.
                      $var=ConvertFrom-Json '$(armOutputs)'
                      $value=$var.saName.value

                      Write-Host "storage account variable"
                      Write-Host "##vso[task.setvariable variable=SANAME;]$value"

                      $sasvalue=$var.serviceSas.value

                      Write-Host "SAS token from ARM output stored in variable SAS"
                      Write-Host "##vso[task.setvariable variable=SAS;]$sasvalue"

                - task: AzureFileCopy@4
                  displayName: Copy setup artefacts to storage account
                  inputs:
                    SourcePath: "$(Pipeline.Workspace)/${{ variables.artifactDropName }}/setupartefacts"
                    azureSubscription: $(azureResourceManagerConnection)
                    Destination: "AzureBlob"
                    storage: $(SANAME)
                    ContainerName: setupartefacts
                    cleanTargetBeforeCopy: true

                - task: AzurePowerShell@5
                  displayName: Install FSLogix with custom script extensions
                  inputs:
                    azureSubscription: $(azureResourceManagerConnection)
                    ScriptType: "InlineScript"
                    errorActionPreference: "stop"
                    azurePowerShellVersion: "LatestVersion"
                    Inline: |
                     write-output "install fslogix extension"
                                       
                     $URI = "https://$(SANAME).blob.core.windows.net/setupartefacts/setupartefacts/cse_installfslogix.ps1?$(SAS)"
                     write-output "$URI"
                                       
                     $vms = '${{ convertToJson(parameters.VMNames) }}' | ConvertFrom-Json
                     $vms
                                       
                     $myjobs = @()
                     foreach ($vm in $vms) {
                         write-output "installing fslogix on vm: $vm"
                                       
                         write-output "$vm"
                         $myjobs += Start-Job -Name "FSLogixOn_$vm" -ScriptBlock {
                             param([string] $VMName,
                                 [string] $CSEURI
                             )
                             $vmres = Get-AzResource -Name $VMName -ResourceType 'Microsoft.Compute/virtualMachines'
                             Set-AzVMCustomScriptExtension -Name 'installFSLogix' -VMName "$VMName" -ResourceGroupName "$($vmres.ResourceGroupName)" -Location "$($vmres.Location)" -Run './setupartefacts/cse_installfslogix.ps1' -FileUri "$CSEURI"
                             Remove-AzVMCustomScriptExtension -Name 'installFSLogix' -VMName "$VMName" -ResourceGroupName "$($vmres.ResourceGroupName)" -Force
                         } -ArgumentList $vm, $URI
                     }
                                       
                     Write-Output "waiting for jobs: $myjobs"
                     do {
                         $running = @($myjobs | Where-Object { $_.State -eq 'Running' })
                         $myjobs | Group-Object State | Select-Object count, name, @{N = 'VMs'; E = { $_.Group.GetEnumerator().name -join ',' } }
                         write-output "-----------------"
                         sleep 5
                     }
                     while ($running.count -gt 0)